services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: true

  Prokl\RequestLogBundle\Service\BitrixBridge\ResponseTransformer:
    class: Prokl\RequestLogBundle\Service\BitrixBridge\ResponseTransformer
    arguments:
      - '@request_log.reponse_logger'
    tags:
      - { name: bitrix.events.init, module: main, event: OnAfterEpilog, method: handle, sort: 1 }

  Prokl\RequestLogBundle\Service\BitrixBridge\ResponseCacher:
    class: Prokl\RequestLogBundle\Service\BitrixBridge\ResponseCacher
    arguments:
      - '@request_log.reponse_logger'
      - '@filesystem'
    tags:
      - { name: bitrix.events.init, module: main, event: OnPageStart, method: handle, sort: 1 }